config/routes.rb
Rails.application.routes.draw do
  get 'user_session/new'
  resources :users
  resources :exhibits
  resources :staffs
  resources :hunts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'application#home'
  get    '/user/login',   to: 'user_session#new'
  post   '/user/login',   to: 'user_session#create'


  get    '/admin/login',   to: 'staff_session#new'
  post   '/admin/login',   to: 'staff_session#create'
  get    '/admin/signup',   to: 'staffs#new'

  get '/logout', to: 'application#destroy_session'

end

app/models/staff.rb
class Staff < ApplicationRecord
  has_secure_password
  has_many :maps
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save { self.email = email.downcase }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
    before_action :set_staff, only: %i[ show edit update destroy ]

  # GET /staffs or /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1 or /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs or /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to staff_url(@staff), notice: "staff was successfully created." }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1 or /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to staff_url(@staff), notice: "staff was successfully updated." }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1 or /staffs/1.json
  def destroy
    @staff.destroy

    respond_to do |format|
      format.html { redirect_to staffs_url, notice: "staff was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def staff_params
      params.require(:staff).permit(:name, :email, :password)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<div style="text-align:center">
<%= form_with(model: staff) do |form| %>
  <% if staff.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% staff.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <p></p>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
  <p></p>
  <div>
  <%= form.label :password, style: "display: block" %>
  <%= form.text_field :password %>
</div>
<p></p>
  <div>
    <%= form.submit %>
  </div>


<% end %>

</div>

app/views/staffs/_staff.html.erb
<div id="<%= dom_id staff %>">
  <p>
    <strong>Name:</strong>
    <%= staff.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= staff.email %>
  </p>


</div>

app/views/staffs/edit.html.erb
<h1>Editing Adminstration</h1>

<%= render "form", user: @staff %>

<br>

<div>
  <%= link_to "Show this user", @staff %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/staffs/new.html.erb
<h1 style="text-align:center">New Administration</h1>

<%= render "form", staff: @staff %>

<br>

app/views/staffs/show.html.erb
<p style="color: green"><%= notice %></p>

<p style="color: green"><%= notice %></p>

<h1>Exhibits</h1>

<div id="exhibits">
  <% Exhibit.all.each do |exhibit| %>
    <%= render exhibit %>
    <p>
      <%= link_to "Show this exhibit", exhibit %>
    </p>
  <% end %>
</div>

<%= link_to "New exhibit", new_exhibit_path %>