config/routes.rb
Rails.application.routes.draw do
  get 'user_session/new'
  resources :users
  resources :exhibits
  resources :staffs
  resources :hunts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'application#home'
  get    '/user/login',   to: 'user_session#new'
  post   '/user/login',   to: 'user_session#create'


  get    '/admin/login',   to: 'staff_session#new'
  post   '/admin/login',   to: 'staff_session#create'
  get    '/admin/signup',   to: 'staffs#new'

  get '/logout', to: 'application#destroy_session'

end

app/models/exhibit.rb
class Exhibit < ApplicationRecord
end

app/controllers/exhibits_controller.rb
class ExhibitsController < ApplicationController
  before_action :set_exhibit, only: %i[ show edit update destroy ]

  # GET /exhibits or /exhibits.json
  def index
    @exhibits = Exhibit.all
  end

  # GET /exhibits/1 or /exhibits/1.json
  def show
    if @exhibit.treasure && current_user
      Hunt.create(user_id: current_user.id, exhibit_id: @exhibit.id)
    end
  end

  # GET /exhibits/new
  def new
    @exhibit = Exhibit.new
  end

  # GET /exhibits/1/edit
  def edit
  end

  # POST /exhibits or /exhibits.json
  def create
    @exhibit = Exhibit.new(exhibit_params)

    respond_to do |format|
      if @exhibit.save
        format.html { redirect_to exhibit_url(@exhibit), notice: "Exhibit was successfully created." }
        format.json { render :show, status: :created, location: @exhibit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibits/1 or /exhibits/1.json
  def update
    respond_to do |format|
      if @exhibit.update(exhibit_params)
        format.html { redirect_to exhibit_url(@exhibit), notice: "Exhibit was successfully updated." }
        format.json { render :show, status: :ok, location: @exhibit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibits/1 or /exhibits/1.json
  def destroy
    @exhibit.destroy

    respond_to do |format|
      format.html { redirect_to exhibits_url, notice: "Exhibit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibit
      @exhibit = Exhibit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exhibit_params
      params.require(:exhibit).permit(:name, :intro, :treasure, :born, :age, :parent, :honor)
    end
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
end

app/views/exhibits/_exhibit.html.erb
<div id="<%= dom_id exhibit %>">
  <p>
    <strong>Name:</strong>
    <%= exhibit.name %>
  </p>

  <p>
    <strong>Intro:</strong>
    <%= exhibit.intro %>
  </p>

  <p>
    <strong>Treasure:</strong>
    <%= exhibit.treasure %>
  </p>

</div>

app/views/exhibits/_form.html.erb
<%= form_with(model: exhibit) do |form| %>
  <% if exhibit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exhibit.errors.count, "error") %> prohibited this exhibit from being saved:</h2>

      <ul>
        <% exhibit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :born, style: "display: block" %>
    <%= form.text_field :born %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :parent, style: "display: block" %>
    <%= form.text_field :parent %>
  </div>

  <div>
    <%= form.label :honor, style: "display: block" %>
    <%= form.text_field :honor %>
  </div>

  <div>
    <%= form.label :intro, style: "display: block" %>
    <%= form.text_field :intro %>
  </div>

  <div>
    <%= form.label :treasure, style: "display: block" %>
    <%= form.check_box :treasure %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exhibits/show.html.erb
    <body>    
        <br>
        <div class="jumbotron">
                <div class="container" style="text-align: center;">
                <h1><%= @exhibit.name%></h1>
            </div>
        </div>

        <div class="container" style="text-align: center;">
            <div class="row">
                <div class="col-sm-4">
                    <img src="https://github.com/SusanLiiii/Museum_Map/blob/main/app/assets/images/watch%20avatar.png?raw=true" class="img-responsive" alt="Responsive image" style="height: 200px;">
                </div>
                <div class="col-sm-8">
                    <p style="font-size: large;">Come and Meet My Friend!</p>
                    <p style="font-size: medium; color:black">Born: <%= @exhibit.born%></p>
                    <p style="font-size: large; color:black">Age: <%= @exhibit.age%></p>
                    <p style="font-size: large; color:black">Parent: <%= @exhibit.parent%></p>
                    <p style="font-size: large; color:black">Honor: <%= @exhibit.honor%></p>
                    <p style="font-size: large; color:black"><%= @exhibit.intro%></p>
                </div>
            </div>
        </div>
        <br>
        
        <% if @exhibit.treasure%>
        <div class="container" style="text-align: center;">
            <div class="row">
                <div class="col-sm-8">
                    <p style="font-size: large; color: green">Congratulations! You have just found a magic egg!</p>
                </div>
            </div>
        </div>
        <% if !logged_in?%>
        <div class="container" style="text-align: center;">
            <div class="row">
                <div class="col-sm-8">
                    <p style="font-size: large; color: red"><%= link_to "Subscribe", user_login_path%> now to get the egg!</p>
                </div>
            </div>
        </div>
        <% end%>
        <%end %>
        <br>
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <a href="https://charles-river-museum.webflow.io/">Back to the map</a>
                </div>
            </div>
    </body>