config/routes.rb
Rails.application.routes.draw do
  get 'user_session/new'
  resources :users
  resources :exhibits
  resources :staffs
  resources :hunts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'application#home'
  get    '/user/login',   to: 'user_session#new'
  post   '/user/login',   to: 'user_session#create'


  get    '/admin/login',   to: 'staff_session#new'
  post   '/admin/login',   to: 'staff_session#create'
  get    '/admin/signup',   to: 'staffs#new'

  get '/logout', to: 'application#destroy_session'

end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, allow_nil: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :phone, allow_nil: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    if !logged_in?
      redirect_to '/user/login'
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :phone)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

    <body>    
        <br>
        <div class="jumbotron">
                <div class="container" style="text-align: center;">
                <h1>Welcome back <%=current_user.name%></h1>
            </div>
        </div>

        <div class="container" style="text-align: center;">
            <div class="row">
                <div class="col-sm-4">
                    <img src="https://mail.google.com/mail/u/0?ui=2&ik=cec2db1fe0&attid=0.3&permmsgid=msg-f:1723974342859995276&th=17ecc987e40eb88c&view=fimg&fur=ip&sz=s0-l75-ft&attbid=ANGjdJ9eqoqMHskbk9w2em1s09bKpgDBrh-biRnPnSESRjDcF5Tqs4vP5OvJ71gLmymono_WWVecGchqd3JsAaIycxG25OyyNPN99vfrFJnmMkTy3U240PVB9Oqxb0A&disp=emb&realattid=ii_kzakloh12" class="img-responsive" alt="Responsive image" style="height: 200px;">
                </div>
                <div class="col-sm-8">
                    <p style="font-size: large;">You have found <%= Hunt.where(user_id:current_user.id).size%> eggs!</p>
                    <p style="font-size: large;">3 eggs will win you a prize!</p>
                    
                </div>
            </div>
        </div>
        <br>
    </body>
<div class="container" style="text-align: center;">
                <a href="https://charles-river-museum.webflow.io/">Click Here to Start the Game!</a>
</div>