config/routes.rb
Rails.application.routes.draw do
  get 'user_session/new'
  resources :users
  resources :exhibits
  resources :staffs
  resources :hunts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'application#home'
  get    '/user/login',   to: 'user_session#new'
  post   '/user/login',   to: 'user_session#create'


  get    '/admin/login',   to: 'staff_session#new'
  post   '/admin/login',   to: 'staff_session#create'
  get    '/admin/signup',   to: 'staffs#new'

  get '/logout', to: 'application#destroy_session'

end

app/controllers/staff_session_controller.rb
class StaffSessionController < ApplicationController
  def new
  end

  def create
    staff = Staff.find_by(email: params[:staff_session][:email])
    if staff && staff.authenticate(params[:staff_session][:password])
      reset_session
      staff_log_in staff
      redirect_to staff
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
end

app/views/staff_session/new.html.erb
<% provide(:title, "Log in") %>


<div class="row" style="text-align:center">
<h1>Log in</h1>
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(url: admin_login_path, scope: :staff_session, local: true) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <p></p>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <p></p>
      <%= f.label :password %>
      <%= f.text_field :password, class: 'form-control' %>
      <p></p>
      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>